version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
        - 27017:27017
    command: mongod --noauth
  webapp:
    build: .
    image: arjunsekar1991/tm-server:latest
    depends_on:
      - "mongo"
    ports:
      - 4000:4000
    volumes:
       - appsystem:/usr/src/app
volumes:
  appsystem:
    driver: local
